### ISSUE TITLE
more info

### ISSUE THREAD

**Issue by ctf0** [groman00/laravel-pwa-boilerplate#1]
can u add more info about how things are working, what has changed ,etc... ?

**Comment by groman00** [comment]
Hi @ctf0,

I set up this boilerplate a few months back as an alternative to using Laravel Mix.  Now that I've gotten more comfortable with Mix, I would recommend that you stick with it instead of implementing a custom frontend.

This project adds [sw-precache](https://github.com/GoogleChrome/sw-precache) and [sw-toolbox](https://github.com/GoogleChrome/sw-toolbox).  You can see how I implemented it with gulp [here](https://github.com/groman00/laravel-pwa-boilerplate/blob/master/gulp/tasks/service-worker.js).

You'll also want to tweak your routes file to return an index.html file, which will be cached by your service worker.  See [web.php](https://github.com/groman00/laravel-pwa-boilerplate/blob/master/routes/web.php).

I'd be happy to answer any specific questions if you have them.  Thanks!

**Comment by ctf0** [comment]
sadly am fairly new into this, so nothing in specific yet, but thanx for ur help :1st_place_medal:
